import { Event } from "./event";

export const EVENTS: Event[] = [
    {
        id: 1,
        date: '2023-01-01',
        startTime: '',
        venue: 'Red Rocks',
        headliner: 'The White Stripes',
        support1: '',
        support2: '',
        support3: '',
        headlinerBio: '',
        headlinerImgLink: '',
        meetsCriteria: '',
        isDenied: '',
        external: '',
        createdAt: '',
        updatedAt: '',
    },
    {
        id: 2,
        date: '2023-01-02',
        startTime: '',
        venue: 'Red Rocks',
        headliner: 'Ween',
        support1: '',
        support2: '',
        support3: '',
        headlinerBio: '',
        headlinerImgLink: '',
        meetsCriteria: '',
        isDenied: '',
        external: '',
        createdAt: '',
        updatedAt: '',
    },
    {
        id: 3,
        date: '2023-01-03',
        startTime: '',
        venue: 'Red Rocks',
        headliner: 'Iron & Wine',
        support1: '',
        support2: '',
        support3: '',
        headlinerBio: '',
        headlinerImgLink: '',
        meetsCriteria: '',
        isDenied: '',
        external: '',
        createdAt: '',
        updatedAt: '',
},
{
        id: 4,
        date: '2023-01-04',
        startTime: '00:00',
        venue: 'Red Rocks',
        headliner: 'Dr. Dog',
        support1: '',
        support2: '',
        support3: '',
        headlinerBio: '',
        headlinerImgLink: '',
        meetsCriteria: '',
        isDenied: '',
        external: '',
        createdAt: '',
        updatedAt: '',
    },
    {
        id: 5,
        date: '2023-01-05',
        startTime: '',
        venue: 'Red Rocks',
        headliner: 'Bill Callahan',
        support1: '',
        support2: '',
        support3: '',
        headlinerBio: '',
        headlinerImgLink: '',
        meetsCriteria: '',
        isDenied: '',
        external: '',
        createdAt: '',
        updatedAt: '',
    },
    {
        id: 6,
        date: '2023-01-06',
        startTime: '',
        venue: 'Red Rocks',
        headliner: 'Modest Mouse',
        support1: '',
        support2: '',
        support3: '',
        headlinerBio: '',
        headlinerImgLink: '',
        meetsCriteria: '',
        isDenied: '',
        external: '',
        createdAt: '',
        updatedAt: '',
      }
]